package com.ras.form;


import static com.formdev.flatlaf.extras.components.FlatButton.ButtonType.tab;
import com.ras.database.DatabaseOperation;
import com.ras.entity.Region;
import com.ras.entity.Table;
import com.ras.enums.TableStatus;
import com.ras.tabbed.TabbedForm;
import com.ras.tabbed.TabbedItem;
import com.ras.tabbed.WindowsTabbed;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingWorker;
import raven.toast.Notifications;



public class RegionManagerForm extends TabbedForm {
    
    public RegionManagerForm() {
        initComponents();
        addRegionButtons();
    }
    
    private void addRegionButtons() {
        
        SwingWorker<Void, Void> worker;
        worker = new SwingWorker<Void, Void>() {

            @Override
            protected Void doInBackground() throws Exception {
                DatabaseOperation databaseOperation = new DatabaseOperation();
                ArrayList<Region> regionList = databaseOperation.getAllRegions();

                JPanel panel = regionPanel;
                int[] siraSutun = calculateTableLayout(regionList.size());
                int sira = siraSutun[0];
                int sutun = siraSutun[1];
                sutun += 2;
                
                
                for(Region r : regionList) {
                    JButton regionButton = new JButton(String.valueOf(r.regionID()));
                    regionButton.setText(r.regionName());

                    regionButton.setActionCommand(String.valueOf(r.regionID()));

                    regionButton.addActionListener(new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent e) {
                            JButton clickedButton = (JButton) e.getSource();
                            String regionName = clickedButton.getText();
                            int regionID = Integer.valueOf(clickedButton.getActionCommand()); 
                            
                            Region region = new Region(regionName, regionID);
                            
                            ArrayList<Table> tableList = databaseOperation.getAllTablesWithSpecificRegion(region);

                            
                            
                            WindowsTabbed.getInstance().addTab("Tables - (" + regionName + ")", new TableManagerForm(tableList));

                            
                            

                        }
                    });
                    panel.add(regionButton);
                }

                panel.setLayout(new GridLayout(sutun, sira, 15, 15));



                return null;
            }

            @Override
            protected void done() {
                try {

                } catch (Exception e) {
                    e.printStackTrace();
                    Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.BOTTOM_LEFT, "404 - Error");
                }
            }
        };
        
        worker.execute();
    }
    
    
    public static int[] calculateTableLayout(int totalTables) {
        int[] dimensions = new int[2]; 

        int rows = 1;
        int columns = 1;

        while (rows * columns < totalTables) {
            if (rows <= columns) {
                rows++;
            } else {
                columns++; 
            }
        }

        dimensions[0] = rows;
        dimensions[1] = columns;

        return dimensions;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        regionPanel = new javax.swing.JPanel();

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel2.setText("Table Manager");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel3.setText("Select a region");

        javax.swing.GroupLayout regionPanelLayout = new javax.swing.GroupLayout(regionPanel);
        regionPanel.setLayout(regionPanelLayout);
        regionPanelLayout.setHorizontalGroup(
            regionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1175, Short.MAX_VALUE)
        );
        regionPanelLayout.setVerticalGroup(
            regionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(477, 846, Short.MAX_VALUE)))
                .addGap(251, 251, 251))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(regionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(regionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel regionPanel;
    // End of variables declaration//GEN-END:variables
}
